### ISSUE TITLE
After a short time using text to speech, it just stops talking. 

### ISSUE THREAD

**Issue by jasonbrock** [JesseVii/TTS#26]
This has been going on since the time that the plugin was removed for a few days from the plugin hub months ago. 
After using text to speech for 5mins-hour it just stops talking.

**Comment by Runewiz** [comment]
I have the same problem... would be nice to get this reliably working.

**Comment by wanieru** [comment]
I noticed the recently added "AltTool"-field in the plugin, and I can see from the source code that if it contains the text "Brian5" and the chosen voice is Susan, it uses a different function and source for the TTS, and this version doesn't have the issue of the TTS stopping working after a while (or the other issue I've been experiencing, with the game freezing before each line of dialogue). Unfortunately it currently always uses the same voice called "Brian".

**Comment by iProdigy** [comment]
@LucyLikesYourFace could you provide a screenshot of the plugin settings or is everything default
