### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Enazalaz** [JesseVii/TTS#28]
I don't know if it is just hackers in runescape or this plugin but i have installed and uninstalled it twice now and both times i've logged out, checked my email and have received emails for a single use code both times meaning someone has been trying to get access through forgot password. i have since uninstalled the plugin and i probably will not be reinstalling it.

Edit: i forgot to mention i have been playing runescape for about a week and a half now, and i haven't had this problem until i installed this plugin.

**Comment by Enazalaz** [comment]
Update: After uninstalling the Plugin, running a Windows Defender scan AND activating 2 factor authentication i have since stopped receiving the emails. I'll install it one last time and if i start receiving them again someone is doing some shady things with this plugin.

**Comment by Enazalaz** [comment]
Update: I've stopped receiving the emails but that doesn't really mean anything. All that tells me is whoever is doing the shady stuff got spooked and stopped. I'll be leaving this plugin uninstalled until access to the 3rd party website my IP is being broadcast to is released.

**Comment by Enazalaz** [comment]
Update: I don't think it's this plugin but i don't know anything about programming or anything so i don't actually know. i have activated 2 factor authentication on my email account, and phone verification so i was told i could safely ignore the emails. but i would seriously like an answer to this. 

I'm sure you would like to know if your own plugin is compromised since it doesn't seem like you're around on github a lot.

**Comment by iProdigy** [comment]
This plugin is incapable of leaking your email; it only contacts ttsplugin.com and readaloud.app with the text to be converted into audio

**Comment by JesseVii** [comment]
All pluginhub plugins are verified to not contain malware like that, and since their open source, you can always re-check yourself.
