### ISSUE TITLE
Mp3Player library creates a thread that stays open forever, the pluging creates an object for every sound.

### ISSUE THREAD

**Issue by wolfsilver00** [JesseVii/TTS#29]
Currently: The issue seems to be related to the library itself as it stays open waiting for a new file to be fed to it, but a new instance of the mp3player is created every time text is processed, which leads to an ungodly amount of threads opened, wasting memory and also connected to the playback device.

Expected: Either eliminate the instance of the mp3player after it has been used (easier) or actually reuse it for follow ups (I think this would be the best solution, as it would avoid recreating a new device and would behave as the rest of the plugins in runelite work.

**Comment by iProdigy** [comment]
In the plugin settings, what have you set `AltTool` to?

`MP3Player` instances are only created if the AltTool config option has been set to `Brian5` (and the voice is Susan)

**Comment by V1del** [comment]
FWIW while the current situation will definitely be better. If you continue to add a file you'll eventually overflow the [underlying vector](https://sourceforge.net/p/jacomp3player/code/HEAD/tree/JACo%20MP3%20Player/src/jaco/mp3/player/MP3Player.java#l87)

I'd suggest you just add the file (since it's always the same name anyway) once, and setRepeat(true) which will make the player repeat the "same" file indefinitely on each play() invocation.

**Comment by iProdigy** [comment]
good point @V1del - the playlist is now cleared to avoid that memory leak https://github.com/JesseVii/TTS/pull/31/commits/521a6535a60a36db7e70a88fcc2fc4d7c1ccc5f2

**Comment by wolfsilver00** [comment]
> In the plugin settings, what have you set `AltTool` to?
> 
> `MP3Player` instances are only created if the AltTool config option has been set to `Brian5` (and the voice is Susan)

AltTool is empty for me

**Comment by iProdigy** [comment]
> AltTool is empty for me and voices are all Lucas

in that case, the MP3Player issue you described wouldn't apply to you in practice

**Comment by wolfsilver00** [comment]
Damn it.. I have to take some time to learn how to build runelite and all that and test the fix, but if the issue only appears with that set-up, then why the hell does this happen without it, maybe something else is triggering it? In all my software (outside runelite) and runelite plugins (ive got 5 that have sounds, so 6 streams generated in total counting runelite itself), only this plugin causes issues

**Comment by V1del** [comment]
Couldn't this also be related to the broken clip logistics you've fixed for #32 ?  Something I also noted when I looked, if it receives the STOP event, it doesn't explciitly close the clip and just nulls away the reference, I'd also see a possibility where the sound device remains if the clip isn't explicitly closed even after it has STOPPED, as a stop doesn't necessarily imply you don't want to reuse the clip at a later point

**Comment by iProdigy** [comment]
yeah [`DirectClip#setAutoClosing`](https://code.yawk.at/java/11/java.desktop/com/sun/media/sound/DirectAudioDevice.java#com.sun.media.sound.DirectAudioDevice.DirectClip%23setAutoClosing%28boolean%29) isn't actually called, so we ought to call close manually to ensure the direct clip [thread](https://code.yawk.at/java/11/java.desktop/com/sun/media/sound/DirectAudioDevice.java#1014) terminates & the clip is removed from the [mixer](https://code.yawk.at/java/11/java.desktop/com/sun/media/sound/AbstractDataLine.java#422) - will update that PR

**Comment by iProdigy** [comment]
not at all @V1del - appreciate the code reviews (there's a fair bit of cleanup still pending) & respek on the forum volunteering

**Comment by wolfsilver00** [comment]
And people say the Arch community is bad hahaha V1del, thanks a lot man, your comments pointed me in the right direction and for some reason I'm learning a bit of java just to understand all of this, so its an absolute win

**Comment by wolfsilver00** [comment]
Little update: I had the Brian5 Alttool thing in my mind for a while, as they are different systems I decided to try using that config..

Incredible enough.. Brian5 with susan voice? No multiple devices... Change back to empty alttool (without even restarting client).. Multiple devices. How is the thing that should be broken fixing it, I dont know.. But it works! (except for the colored text, it "reads" the color tags of the notifications haha weird

**Comment by V1del** [comment]
Technically speaking both implementations are somewhat broken currently, it's likely the logistics the JacoPlayer uses are ultimately sharing the same underlying device but it's still going to create unnecessary background threads that are likely to stick around and eat resources unnecessarily. 

It was simply the first thing that stuck to me when I looked but I also noted issues with the clip implementation a bit later (in the patch I gave you in the thread I try to bypass this somewhat by running a close() on the clip when it adds a listener.
